Modification related to EBS data volume replacement
scalar-labs/scalar-terraform pull request #195
Opened 2020-09-02 07:50 UTC by scalar-boney

Cassandra node replacement doc updated for EBS data volume crash recovery.

- Cassandra node replacement with taint volume (Need to remove newly created node IP from seeds before restarting the new node).

- Replace the seeds of all Cassandra nodes after Cassandra node replacement(Replace newly created node IP).

2020-09-03 01:32 UTC, tei-k commented on docs/CassandraOperation.md
> +  * Remove the newly created cassandra node IP from the newly created cassandra node seeds.
[Q] just remove ip from the newly created node? or all each nodes if replace node is seed node?

https://docs.datastax.com/en/ddac/doc/datastax_enterprise/operations/opsReplaceNode.html

2020-09-03 01:38 UTC, feeblefakie requested changes

2020-09-03 01:38 UTC, feeblefakie commented on docs/CassandraOperation.md
> +  * Remove the newly created cassandra node IP from the newly created cassandra node seeds.
```suggestion
* Remove the newly created Cassandra node IP from the seeds of the node.
```

2020-09-03 01:38 UTC, feeblefakie commented on docs/CassandraOperation.md
> +sudo systemctl restart cassandra
```suggestion
```

2020-09-03 01:38 UTC, feeblefakie commented on docs/CassandraOperation.md
>  * Finally you can start the Cassandra service.
```suggestion
Finally you can start the Cassandra service.
```

2020-09-04 01:53 UTC, scalar-boney commented on docs/CassandraOperation.md
> +  * Remove the newly created cassandra node IP from the newly created cassandra node seeds.
@tei-k san,
> just remove ip from the newly created node? or all each nodes if replaced node was seed node?

Before restarting the newly created node, We need to remove the newly created node IP from the `seeds` of newly created node.
Note:- It is applicable only for seed nodes. We can skip this step when the newly created node is a `non-seed` node.

2020-09-04 02:12 UTC, scalar-boney commented on docs/CassandraOperation.md
> +* After a successful restart of the newly created Cassandra node, you should replace the seeds of all Cassandra nodes with newly created Cassandra node IP and restart the Cassandra nodes.
> What do you mean by this?

All other Cassandra node seeds contain IP address of the old node(crashed node) When we replace a seed node. So we need to replace the IP address in all other Cassandra node seeds.

> I think non replaced nodes don't have the new node IP in the seeds list, doesn't it?

yes, We do not need to update the seeds for non replaced nodes

2020-09-04 02:29 UTC, scalar-boney commented on docs/CassandraOperation.md
> +* After a successful restart of the newly created Cassandra node, you should replace the seeds of all Cassandra nodes with newly created Cassandra node IP and restart the Cassandra nodes.
Thank you for the review comment.
Document updated with the above change.

2020-09-04 03:23 UTC, yito88 commented on docs/CassandraOperation.md
> +  * Remove the newly created cassandra node IP from the newly created cassandra node seeds.
Just curious. Is there another seed in this case? Can a new node join the cluster without removing the IP from its `seeds` parameter if other seeds are alive?

2020-09-04 03:38 UTC, yito88 commented on docs/CassandraOperation.md
> +* After a successful restart of the newly created Cassandra node, you should replace the seeds of all Cassandra nodes with newly created Cassandra node IP and restart the Cassandra nodes.
I think that we don't need to make the new node a seed node. The new node might not be able to be accessed because the new node will have a heavy load to sync the data of the cluster.

I have two scenarios to replace a seed node. I'm not sure which case you tested.
### A) A cluster has only one seed node. The seed node is dead and we need to replace the node.
- The cluster has no living seed node, so, a new node can't join the cluster.
- Before replacing, we need to promote an existing node to a seed node. (We can remove the dead seed node's IP from other nodes in this promotion). After this promotion, this case will become a case where replacing a non-seed node.

### B) A cluster has multiple seed nodes. One of the seed nodes is dead and we replace it.
- A new node can join the cluster as a non-seed node.

According to the [document](https://docs.datastax.com/en/cassandra-oss/2.1/cassandra/operations/opsReplaceNode.html#Replacingadeadseednode), DataStax recommends promoting a non-seed node before replacing the dead seed node.

2020-09-04 03:48 UTC, yito88 commented on docs/CassandraOperation.md
> +* After a successful restart of the newly created Cassandra node, you should replace the seeds of all Cassandra nodes with newly created Cassandra node IP and restart the Cassandra nodes.
Sorry, the document is too old.
The current [document](https://docs.datastax.com/en/cassandra-oss/3.x/cassandra/operations/opsReplaceNode.html) says that a new node joins the cluster as a new seed node.

2020-09-04 05:56 UTC, scalar-boney commented on docs/CassandraOperation.md
> +  * Remove the newly created cassandra node IP from the newly created cassandra node seeds.
> Is there another seed in this case? 

Yes, In this case, other two `seed` nodes are available.

> Can a new node join the cluster without removing the IP from its seeds parameter if other seeds are alive?

Do you mean, 
Is it possible to add a new node in the cluster while one seed node crashed in the cluster?

2020-09-04 06:04 UTC, yito88 commented on docs/CassandraOperation.md
> +  * Remove the newly created cassandra node IP from the newly created cassandra node seeds.
> Is it possible to add a new node in the cluster while one seed node crashed in the cluster?
No. Can a new node with which the seed node was replaced join to the cluster without removing the seed's IP?
You removed the seed's IP from the config file of the new node in your test. I'd like to know what happens in the bootstrapping when it is NOT removed.

2020-09-04 08:18 UTC, scalar-boney commented on docs/CassandraOperation.md
> +  * Remove the newly created cassandra node IP from the newly created cassandra node seeds.
> Can a new node with which the seed node was replaced join to the cluster without removing the seed's IP? 

yes, But both nodes will show in the cluster. (Old node status is `DN`)

> I'm wondering whether the new node checks another seed or not.
You removed the seed's IP from the config file of the new node in your test. I'd like to know what happens in the bootstrapping when it is NOT removed.

Bootstrapping will happens while the seeds are not replaced.

2020-09-04 09:26 UTC, yito88 commented on docs/CassandraOperation.md
> +  * Remove the newly created cassandra node IP from the newly created cassandra node seeds.
The terraform module automatically adds the new node's IP to `seeds` in the config file. So, we need to remove the IP from the `seeds` explicitly and restart the new node with `replace_address_first_boot` option. I got it.

2020-09-07 00:07 UTC, feeblefakie approved these changes
If the suggestions are applied, LGTM.

2020-09-07 00:07 UTC, feeblefakie commented on docs/CassandraOperation.md
> +You also need to modify the file `/etc/cassandra/conf/cassandra.yaml` If you replaced a seed node and a volume.
```suggestion
You also need to modify the file `/etc/cassandra/conf/cassandra.yaml` if you replaced a seed node and a volume.
```

2020-09-07 00:07 UTC, feeblefakie commented on docs/CassandraOperation.md
> +If you replaced a seed node, you should replace the seeds of all Cassandra nodes with newly created Cassandra node IP.
```suggestion
If you replaced a seed node (old seed node), you should replace the old seed node's IP of all Cassandra nodes with newly created Cassandra node IP.
```

2020-09-08 00:15 UTC, tei-k approved these changes
LGTM!

2020-09-08 00:25 UTC, merged