Troubleshoot guide for node replacement
scalar-labs/scalar-terraform pull request #205
Opened 2020-09-14 06:13 UTC by scalar-boney

Troubleshoot guide for node replacement
- Replace accidentally removed node or os-disk
- Replace accidentally removed Cassandra node or os-disk with existing data disk

2020-09-15 00:45 UTC, feeblefakie requested changes

2020-09-15 00:45 UTC, feeblefakie commented on docs/TroubleshootingGuide.md
> +# Troubleshoot Guide
```suggestion
# Troubleshooting Guide
```

2020-09-15 00:45 UTC, feeblefakie commented on docs/TroubleshootingGuide.md
> +This guide explains how to replace a node when the node cannot be replaced with normal procedures. This is especially useful when the node or os-disk is accidentally terminated in the **Azure** envir
It should be a general troubleshooting guide, so it's weird to see one of the cases in the introductory sentence. It should be just one of the cases.

2020-09-15 11:36 UTC, scalar-boney commented on docs/TroubleshootingGuide.md
> +This guide explains how to replace a node when the node cannot be replaced with normal procedures. This is especially useful when the node or os-disk is accidentally terminated in the **Azure** envir
Sorry for the inconvenience.
Document modified based on the review comment.

2020-09-16 05:27 UTC, feeblefakie requested changes

2020-09-16 05:27 UTC, feeblefakie commented on docs/TroubleshootingGuide.md
> +## Node Replacement
Very misleading. It can be interpreted as that node replacement is one of the troubleshooting, which is not correct.

```suggestion
## Accidental deletion of resources
```

Update the other titles accordingly.

2020-09-17 01:03 UTC, feeblefakie requested changes
Overall the doc is too specific to what you did and not really generalized and formatted as a troubleshooting guide.
I left some suggestions on only part of it but anyways please update all based on them.
The point is that the readers of the doc don't really know what you did, and faced some troubles and came here to fix the troubles. Please assume that.

2020-09-18 00:16 UTC, tei-k commented on docs/TroubleshootingGuide.md
> +* Terminate the node If the os-disk is deleted.
Is this is a very rare case ? I think we can't delete only os-disk from console. 🤔

2020-09-18 01:04 UTC, scalar-boney commented on docs/TroubleshootingGuide.md
> +These troubleshooting steps can be used when the node cannot be replaced with normal procedures. This is especially useful when the node or os-disk is accidentally terminated in the **Azure** environ
Thank you for your suggestion.
Review changes updated.

2020-09-18 01:05 UTC, scalar-boney commented on docs/TroubleshootingGuide.md
> +### Replace accidentally removed node or os-disk
Thank you for your suggestion.
Review changes updated.

2020-09-18 01:06 UTC, scalar-boney commented on docs/TroubleshootingGuide.md
> +### Replace accidentally removed cassandra node or os-disk with existing data disk
Thank you for your suggestion.
Review changes updated.

What do you mean os-disk with existing data disk ?
Sorry for the inconvenience.
I mean recover accidentally removed node with existing data disk.

2020-09-18 01:09 UTC, scalar-boney commented on docs/TroubleshootingGuide.md
> +* Terminate the node If the os-disk is deleted.
Thank you for your valuable comment.
Yes, It is not possible through the console because os-disk deletion not possible without terminating VM. 

I have modified the document accordingly.

2020-09-23 05:51 UTC, feeblefakie requested changes

2020-09-23 05:51 UTC, feeblefakie commented on docs/TroubleshootingGuide.md
> +### Recover from accidental deletion of a node
Is it needed for AWS as well? Only for Azure?
It must be described.

2020-09-23 06:11 UTC, scalar-boney commented on docs/TroubleshootingGuide.md
> +### Recover from accidental deletion of a node
> Is it needed for AWS as well? 

no

> Only for Azure?

yes

> It must be described.

Document modified respectively.
```
When you accidentally delete a resource manually without terraform, it causes some inconsistencies between the actual state of resources and the state that terraform knows. Thus, you might need to take some extra actions to recover from such situations depending on the Cloud you use. The following explains how to recover from such cases in the AZURE scalar-terraform environment.
```

2020-09-23 06:23 UTC, feeblefakie requested changes

2020-09-23 06:23 UTC, feeblefakie commented on docs/TroubleshootingGuide.md
> +When you accidentally delete a resource manually without terraform, it causes some inconsistencies between the actual state of resources and the state that terraform knows. Thus, you might need to ta
This sentence is a general one. Write `azure` thing in each section below.

2020-09-23 06:23 UTC, feeblefakie commented on docs/TroubleshootingGuide.md
> +- Recover from accidental deletion of a node
We don't need the list.

2020-09-23 06:23 UTC, feeblefakie commented on docs/TroubleshootingGuide.md
> +### Recover from accidental deletion of a node
```suggestion
### Recover from accidental deletion of a node in Azure
```

2020-09-23 06:23 UTC, feeblefakie commented on docs/TroubleshootingGuide.md
> +### Recover a node with existing data disk from accidental deletion of a node
```suggestion
### Recover a node with existing data disk from accidental deletion of a node in Azure
```

2020-09-23 06:23 UTC, feeblefakie commented on docs/TroubleshootingGuide.md
> +If you accidentally delete a node that does not have an additional data disk, you can recover it in the following steps. It is mainly applicable for scalardl, envoy, cassy, reaper, monitor and ca nod
```suggestion
If you accidentally delete a node that does not have an additional data disk in Azure, you can recover it in the following steps. It is mainly applicable for scalardl, envoy, cassy, reaper, monitor and ca nodes.
```

2020-09-23 06:23 UTC, feeblefakie commented on docs/TroubleshootingGuide.md
> +If you accidentally delete a node that contains an additional data disk, you can recover that node with an existing data disk using the following steps.
```suggestion
If you accidentally delete a node that contains an additional data disk in Azure, you can recover that node with an existing data disk using the following steps.
```

2020-09-23 06:23 UTC, feeblefakie commented on docs/TroubleshootingGuide.md
> +When you accidentally delete a resource manually without terraform, it causes some inconsistencies between the actual state of resources and the state that terraform knows. Thus, you might need to ta
```suggestion
When you accidentally delete a resource manually without terraform, it causes some inconsistencies between the actual state of resources and the state that terraform knows. Thus, you might need to take some extra actions to recover from such situations depending on the Cloud you use.
```

2020-09-23 06:49 UTC, scalar-boney commented on docs/TroubleshootingGuide.md
> +When you accidentally delete a resource manually without terraform, it causes some inconsistencies between the actual state of resources and the state that terraform knows. Thus, you might need to ta
Thank you for your suggestion.
Document updated with suggestion details.

2020-09-23 06:49 UTC, scalar-boney commented on docs/TroubleshootingGuide.md
> +If you accidentally delete a node that contains an additional data disk, you can recover that node with an existing data disk using the following steps.
Thank you for your suggestion.
Document updated with suggestions.

2020-09-23 06:50 UTC, scalar-boney commented on docs/TroubleshootingGuide.md
> +If you accidentally delete a node that does not have an additional data disk, you can recover it in the following steps. It is mainly applicable for scalardl, envoy, cassy, reaper, monitor and ca nod
Thank you for your suggestion.
Document updated with suggestions.

2020-09-23 06:50 UTC, scalar-boney commented on docs/TroubleshootingGuide.md
> +### Recover a node with existing data disk from accidental deletion of a node
Thank you for your suggestion.
Document updated with suggestions.

2020-09-23 06:51 UTC, scalar-boney commented on docs/TroubleshootingGuide.md
> +### Recover from accidental deletion of a node
Thank you for your suggestion.
Document updated with suggestions.

2020-09-23 06:52 UTC, scalar-boney commented on docs/TroubleshootingGuide.md
> +- Recover from accidental deletion of a node
Thank you for your suggestion.
document updated without list.

2020-09-23 06:53 UTC, scalar-boney commented on docs/TroubleshootingGuide.md
> +When you accidentally delete a resource manually without terraform, it causes some inconsistencies between the actual state of resources and the state that terraform knows. Thus, you might need to ta
Sorry for the inconvenience.
Document updated with suggestions.

2020-09-25 00:42 UTC, feeblefakie approved these changes
LGTM

2020-09-25 00:42 UTC, merged