Document modification: EBS data volume replacement
scalar-labs/scalar-terraform pull request #216
Opened 2020-09-29 11:09 UTC by scalar-boney

Cassandra EBS data volume replacement steps modified with some additional steps.
- New steps added for EBS data volume replacement with existing node.
- Cassy backup restoration steps modified `Case3: Node and the volume are both replaced`

2020-10-05 02:20 UTC, tei-k commented on docs/CassandraOperation.md
> +The other option is to taint the volume which should be used as a last resort. This *will permanently delete data* on that volume and attach recreated volume with existing node. Be sure you can recov
In part `### Taint Volume (with node replacement)`,  it explicitly says `data volume`, what's the difference?

2020-10-05 02:26 UTC, tei-k commented on docs/CassandraOperation.md
> +* Replace the UUID of the `data` volume in `fstab`.
Is this just for data volume? Can we use the same procedure for commit volume?

2020-10-06 00:51 UTC, scalar-boney commented on docs/CassandraOperation.md
> +The other option is to taint the volume which should be used as a last resort. This *will permanently delete data* on that volume and attach recreated volume with existing node. Be sure you can recov
> In part ### Taint Volume (with node replacement), it explicitly says data volume, what's the difference?

In part `Taint volume`, it handles both data or commitlog volume replacement.

Thank you for the review comments.
The document updated accordingly.

2020-10-06 00:52 UTC, scalar-boney commented on docs/CassandraOperation.md
> +* Replace the UUID of the `data` volume in `fstab`.
> Is this just for data volume? 

No

> Can we use the same procedure for commit volume?

Yes

Thank you for the review comments.
The document updated accordingly.

2020-10-08 00:36 UTC, scalar-boney commented on docs/CassandraOperation.md
> +The other option is to taint the volume which should be used as a last resort. This *will permanently delete data* on that volume and attach the recreated data or commit log volume to the already exi
Both options are true,
First option, replacing the instance along with taint volume.
Second option, only replacing taint volume. means it does not replace the node.

2020-10-08 11:58 UTC, feeblefakie requested changes

2020-10-08 11:58 UTC, feeblefakie commented on docs/CassandraOperation.md
> +##### Azure
Indenting is too deep. Should come up with a better way.

2020-10-08 11:58 UTC, feeblefakie commented on docs/CassandraOperation.md
> -The other option is to taint the volume which should be used as a last resort. This *will permanently delete data* on that volume. Be sure you can recover the data from a backup first.
I think you changed the context.
The original doc says `taint attachment` or `taint volume`. 
If it is removed, users can't follow it any more.

2020-10-08 11:58 UTC, feeblefakie commented on docs/CassandraOperation.md
> +There are two other options for replacing the taint volume as a last resort.
What do you mean `replacing the taint volume`?

2020-10-08 11:58 UTC, feeblefakie commented on docs/CassandraOperation.md
>  ```
The updated document got too many branches so it's pretty difficult to properly follow.
I think it needs to be reorganized to include a new case.
```
* Case 1
** Replace a resource
** Restart Cassandra
* Case 2 
** Replace a resource
** Restart Cassandra
...
```

2020-10-09 05:27 UTC, scalar-boney commented on docs/CassandraOperation.md
> -The other option is to taint the volume which should be used as a last resort. This *will permanently delete data* on that volume. Be sure you can recover the data from a backup first.
Sorry, Orginal doc also says [Taint Volume](https://github.com/scalar-labs/scalar-terraform/blob/master/docs/CassandraOperation.md#taint-volume)

2020-10-09 06:12 UTC, scalar-boney commented on docs/CassandraOperation.md
> +##### Azure
The document updated accordingly.

2020-10-09 06:19 UTC, scalar-boney commented on docs/CassandraOperation.md
> +There are two other options for replacing the taint volume as a last resort.
Sorry for the inconvenience.
Here I mean, replace the corrupted volume with the `taint` command.

Document modified.

2020-10-09 06:20 UTC, scalar-boney commented on docs/CassandraOperation.md
>  ```
@feeblefakie san,
Thank you for the suggestion.
The document updated accordingly.

2020-10-12 08:30 UTC, tei-k commented on docs/CassandraOperation.md
> +### Case 1: Taint volume attachment
`Case 2 and Case 3` uses `Taint Volume`.
`Taint volume` or `Taint Volume` Which is correct?

---
📝 

Case 1 : Replace `VM` only
Case 2: Replace `VM` and `Volume`
Case 3: Replace `Volume` only

2020-10-12 08:30 UTC, tei-k submitted a review, later dismissed
LGTM!

2020-10-12 10:49 UTC, scalar-boney commented on docs/CassandraOperation.md
> +### Case 1: Taint volume attachment
@tei-k san,
Thank you for the detailed checking.

> Taint volume or Taint Volume Which is correct?

`Taint volume` is correct.
The document updated accordingly.

2020-10-12 11:37 UTC, feeblefakie requested changes
Left suggestions.

2020-10-12 11:37 UTC, feeblefakie commented on docs/CassandraOperation.md
>  When you taint the volume attachment terraform will try to attach the same data or commit log volume to the new instance. This is the ideal situation as it is the quickest way to replace a node.
```suggestion
When a node (VM or instance) is not working properly for some reason but the volume is fully functioning, only the node should be replaced with a new one.
You can replace the node by tainting the VM or the instance and the volume attachment as described below.
Note that, when you taint the volume attachment terraform will try to attach the same data or commit log volume to the new instance. 
```

2020-10-12 11:37 UTC, feeblefakie commented on docs/CassandraOperation.md
> +### Case 2: Taint volume with node replacement
```suggestion
### Case 3: Replace both a node and the volume
```
Also, this should come at the end.

2020-10-12 11:37 UTC, feeblefakie commented on docs/CassandraOperation.md
> +### Case 3: Taint volume without node replacement
```suggestion
### Case 2: Replace the volume of a node, but not the node
```

2020-10-12 11:37 UTC, feeblefakie commented on docs/CassandraOperation.md
> +Another option is to taint the volume which should be used as a last resort. This *will permanently delete data* on that volume and attach the recreated data or commit log volume to the already exist
```suggestion
When the volume is not functioning properly for some reason but the node is alive, only the volume should be replaced with a new one.
You can replace the volume by tainting the volume as described below.
Note that this *will permanently delete data* on that volume and attach the recreated data or commit log volume to the already existing node. When you do this, it is recommended to recover data from backup.
```

2020-10-12 11:37 UTC, feeblefakie commented on docs/CassandraOperation.md
> +The other option is to taint the volume which should be used as a last resort. This *will permanently delete data* on that volume and it will recreate the node along with data or commit log volume. B
```suggestion
When both a node and the volume are not working properly, both resources should be replaced with new ones.
You can do it by tainting both resources as described below.
Since the volume is replaced as the 2nd option, this *will permanently delete data* on that volume.
```

2020-10-12 13:51 UTC, scalar-boney commented on docs/CassandraOperation.md
>  * You also need to decide to taint either the *drive attachment* or the *volume* directly.
Thank you for the review comment.
The document updated accordingly.

2020-10-12 13:51 UTC, scalar-boney commented on docs/CassandraOperation.md
Thank you for the review comment.
The document updated accordingly.

2020-10-12 13:52 UTC, scalar-boney commented on docs/CassandraOperation.md
> +### Case 1: Taint volume attachment
Thank you for the review comment.
The document updated accordingly.

2020-10-12 13:52 UTC, scalar-boney commented on docs/CassandraOperation.md
>  When you taint the volume attachment terraform will try to attach the same data or commit log volume to the new instance. This is the ideal situation as it is the quickest way to replace a node.
Thank you for the review comment.
The document updated accordingly.

2020-10-12 13:52 UTC, scalar-boney commented on docs/CassandraOperation.md
> +### Case 2: Taint volume with node replacement
Thank you for the review comment.
The document updated accordingly.

2020-10-12 13:52 UTC, scalar-boney commented on docs/CassandraOperation.md
> +### Case 3: Taint volume without node replacement
Thank you for the review comment.
The document updated accordingly.

2020-10-12 13:52 UTC, scalar-boney commented on docs/CassandraOperation.md
> +Another option is to taint the volume which should be used as a last resort. This *will permanently delete data* on that volume and attach the recreated data or commit log volume to the already exist
Thank you for the review comment.
The document updated accordingly.

2020-10-12 13:52 UTC, scalar-boney commented on docs/CassandraOperation.md
> +The other option is to taint the volume which should be used as a last resort. This *will permanently delete data* on that volume and it will recreate the node along with data or commit log volume. B
Thank you for the review comment.
The document updated accordingly.

2020-10-13 01:28 UTC, feeblefakie reviewed
Left additional suggestions. Almost good to go.

2020-10-13 01:28 UTC, feeblefakie commented on docs/CassandraOperation.md
> +#### Post Recovery Steps
```suggestion
#### Post Terraform Steps
```
Please update the others.

2020-10-13 01:28 UTC, feeblefakie commented on docs/CassandraOperation.md
> +Note that, when you taint the volume attachment terraform will try to attach the same data or commit log volume to the new instance.
```suggestion
Note that, when you taint the volume attachment, terraform will try to attach the same data or commit log volume to the new instance.
```

2020-10-13 01:28 UTC, feeblefakie commented on docs/CassandraOperation.md
> +Note that this *will permanently delete data* on that volume and attach the recreated data or commit log volume to the already existing node.
```suggestion
Note that this *will permanently delete data* on that volume and attach the recreated data or commit log volume to the existing node. 
```

2020-10-13 01:28 UTC, feeblefakie commented on docs/CassandraOperation.md
> +Since the volume is replaced as the 2nd option, this *will permanently delete data* on that volume.
```suggestion
Since the volume is replaced in the same manner as the 2nd option, the data on that volume will be permanently deleted.
```

2020-10-13 01:49 UTC, scalar-boney commented on docs/CassandraOperation.md
> +#### Post Recovery Steps
Thank you for the review suggestions.
The document updated accordingly.

2020-10-13 01:49 UTC, scalar-boney commented on docs/CassandraOperation.md
> +Note that, when you taint the volume attachment terraform will try to attach the same data or commit log volume to the new instance.
Thank you for the review suggestions.
The document updated accordingly.

2020-10-13 01:49 UTC, scalar-boney commented on docs/CassandraOperation.md
> +Note that this *will permanently delete data* on that volume and attach the recreated data or commit log volume to the already existing node.
Thank you for the review suggestions.
The document updated accordingly.

2020-10-13 01:49 UTC, scalar-boney commented on docs/CassandraOperation.md
> +Since the volume is replaced as the 2nd option, this *will permanently delete data* on that volume.
Thank you for the review suggestions.
The document updated accordingly.

2020-10-15 00:37 UTC, ymorimo reviewed
Sorry for late. Left some comments.

2020-10-15 00:37 UTC, ymorimo commented on docs/CassandraOperation.md
> +  enable_data_volume        = true
Please remove the trailing white spaces.

2020-10-15 00:37 UTC, ymorimo commented on docs/CassandraOperation.md
> +```console
Please remove the trailing white space.

2020-10-15 00:37 UTC, ymorimo commented on docs/CassandraOperation.md
> +### Case 2: Replace the volume of the node, but not the node
Isn't it needed to stop Cassandra before replacing the volume with terraform taint & apply?

2020-10-15 05:16 UTC, scalar-boney commented on docs/CassandraOperation.md
> +### Case 2: Replace the volume of the node, but not the node
Cassandra node stops automatically when data volume is corrupted (delete the data volume).
So, the current steps are working fine without stopping the nodes manually.

2020-10-15 05:22 UTC, scalar-boney commented on docs/CassandraOperation.md
> +  enable_data_volume        = true
Thank you for the review comments.
Unwanted whitespace removed.

2020-10-15 05:22 UTC, scalar-boney commented on docs/CassandraOperation.md
> +```console
Thank you for the review comments.
Unwanted whitespace removed.

2020-10-19 01:25 UTC, feeblefakie approved these changes
LGTM! Thanks.

2020-10-19 01:25 UTC, merged