Scalar-terraform and scalar-k8s resource usage matrix
scalar-labs/scalar-terraform pull request #221
Opened 2020-10-01 11:51 UTC by scalar-boney

Scalar-terraform and scalar-k8s resource usage matrix created.

2020-10-06 02:07 UTC, feeblefakie reviewed
Overall looking good. Left some comments.

2020-10-08 01:53 UTC, scalar-boney commented on docs/ResourceUsage.md
> +Base: _chiku_
Thank you for your review comments.
> Is it needed?

No,
The document has been updated accordingly.

2020-10-08 01:54 UTC, scalar-boney commented on docs/ResourceUsage.md
> +Base: _chiku_
The document has been updated accordingly.

2020-10-08 01:54 UTC, scalar-boney commented on docs/ResourceUsage.md
> +Base: _bai_
The document has been updated accordingly.

2020-10-08 01:54 UTC, scalar-boney commented on docs/ResourceUsage.md
> +Base: _bai_
The document has been updated accordingly.

2020-10-08 01:54 UTC, scalar-boney commented on docs/ResourceUsage.md
> +Scalar-terraform and scalar-k8s resource usage and price details available here. Resource usage price calculated on monthly basis.
Thank you for the review comment.
The document has been updated accordingly.

2020-10-08 12:03 UTC, feeblefakie requested changes

2020-10-08 12:03 UTC, feeblefakie commented on docs/ResourceUsage.md
> +## Scalar-terraform resource usage
It should note that the numbers are from the default settings.

2020-10-08 12:03 UTC, feeblefakie commented on docs/ResourceUsage.md
> +#### **Chiku**
Indenting is too deep. 
Why don't you separate the doc into 2 files; terraform and k8s.

2020-10-09 04:12 UTC, scalar-boney commented on docs/ResourceUsage.md
> +## Scalar-terraform resource usage
@feeblefakie san,
Sorry,
In the AWS scalar-terraform, the default `bastion_resource_count` is 2 but here we calculated the cost for only one bastion resource.

Is it need to calculate the cost for 2 bastion resources?

In Azure scalar-terraform, the default value of  `bastion_resource_count` is 1

2020-10-09 04:35 UTC, scalar-boney commented on docs/ResourceUsage.md
> +#### **Chiku**
Thank you for your suggestion.
The resource usage matrix is ​​split into 2.
- [TerraformResourceUsage.md](https://github.com/scalar-labs/scalar-terraform/blob/resource_usage_matrix/docs/TerraformResourceUsage.md)
- [K8SResourceUsage.md](https://github.com/scalar-labs/scalar-terraform/blob/resource_usage_matrix/docs/K8SResourceUsage.md)

2020-10-12 05:43 UTC, feeblefakie approved these changes
LGTM. Thanks.

2020-10-12 05:43 UTC, merged