Update troubleshooting guide
scalar-labs/scalar-terraform pull request #308
Opened 2021-05-06 01:39 UTC by scalar-boney

Update troubleshooting guide

* `terraform refresh` shows the following error
```
module.cassandra.azurerm_virtual_machine_data_disk_attachment.cassandra_data_volume_attachment[0]: Refreshing state... [id=/subscriptions/b647bf0e-0566-4b28-ac8c-37b24f3b7061/resourceGroups/psim-azure-hvidlnk/providers/Microsoft.Compute/virtualMachines/cassandra-1/dataDisks/data-disk-cassandra0]
module.cassandra.azurerm_virtual_machine_data_disk_attachment.cassandra_data_volume_attachment[2]: Refreshing state... [id=/subscriptions/b647bf0e-0566-4b28-ac8c-37b24f3b7061/resourceGroups/psim-azure-hvidlnk/providers/Microsoft.Compute/virtualMachines/cassandra-3/dataDisks/data-disk-cassandra2]
module.cassandra.azurerm_virtual_machine_data_disk_attachment.cassandra_data_volume_attachment[1]: Refreshing state... [id=/subscriptions/b647bf0e-0566-4b28-ac8c-37b24f3b7061/resourceGroups/psim-azure-hvidlnk/providers/Microsoft.Compute/virtualMachines/cassandra-2/dataDisks/data-disk-cassandra1]
module.cassandra.module.cassandra_provision.null_resource.cassandra[2]: Refreshing state... [id=196610524335755786]
module.cassandra.module.cassandra_provision.null_resource.cassandra[0]: Refreshing state... [id=7697572524007658753]
module.cassandra.module.cassandra_provision.null_resource.cassandra[1]: Refreshing state... [id=3515917159123694899]

Error: Virtual Machine "cassandra-1" (Resource Group "psim-azure-hvidlnk") was not found

Releasing state lock. This may take a few moments...
```

* Node with data disk recovery also failed while using the following commands
```
terraform taint "module.cassandra.module.cassandra_cluster.azurerm_virtual_machine.vm-linux[0]"
terraform taint "module.cassandra.azurerm_managed_disk.cassandra_data_volume[0]"

terraform apply
```

2021-05-07 01:58 UTC, tei-k commented on docs/TroubleshootingGuide.md
> +Follow [Cassandra Post Recovery Steps](CassandraOperation.md#post-terraform-steps)
```suggestion
Follow [Cassandra Post Terraform Steps](CassandraOperation.md#post-terraform-steps)
```

2021-05-07 02:17 UTC, tei-k commented on docs/TroubleshootingGuide.md
> +Follow [Cassandra Post Recovery Steps](CassandraOperation.md#post-terraform-steps-2)
```suggestion
Follow [Cassandra Post Terraform Steps](CassandraOperation.md#post-terraform-steps-2)
```

2021-05-07 02:49 UTC, scalar-boney commented on docs/TroubleshootingGuide.md
> +Follow [Cassandra Post Recovery Steps](CassandraOperation.md#post-terraform-steps)
Thank you for your suggestion.
Document updated accordingly.

2021-05-07 02:49 UTC, scalar-boney commented on docs/TroubleshootingGuide.md
> +Follow [Cassandra Post Recovery Steps](CassandraOperation.md#post-terraform-steps-2)
Thank you for your suggestion.
Document updated accordingly.

2021-05-07 03:06 UTC, tei-k approved these changes
LGTM!

2021-05-10 00:12 UTC, feeblefakie requested changes
Left some comments.

2021-05-10 00:12 UTC, feeblefakie commented on docs/TroubleshootingGuide.md
> +### Recover a node with data disk from accidental deletion of a node and data disk in Azure
Is this step only required in Azure? (no action needed for AWS?)

2021-05-10 00:12 UTC, feeblefakie commented on docs/TroubleshootingGuide.md
> +### Recover a node with data disk from accidental deletion of a node and data disk in Azure
Also, are you talking about a case where both the node and the data disk are deleted?
If so, the sentence doesn't sound like it.
```suggestion
### Recover a node with a data disk from accidental deletion of both the node and the data disk in Azure
```

2021-05-10 00:12 UTC, feeblefakie commented on docs/TroubleshootingGuide.md
> +Please try the following
You've already said `using the following steps` in the above sentence. Isn't it redundant?
(If you just copied without thinking, please don't do that)

2021-05-10 09:52 UTC, scalar-boney commented on docs/TroubleshootingGuide.md
> +### Recover a node with data disk from accidental deletion of a node and data disk in Azure
> Is this step only required in Azure? (no action needed for AWS?)

Yes, It is only required for Azure

2021-05-10 09:55 UTC, scalar-boney commented on docs/TroubleshootingGuide.md
> +### Recover a node with data disk from accidental deletion of a node and data disk in Azure
> Also, are you talking about a case where both the node and the data disk are deleted?

Yes,
Above suggestion updated in the document. 
Thank you for the suggestion.

2021-05-10 10:02 UTC, scalar-boney commented on docs/TroubleshootingGuide.md
> +Please try the following
> You've already said using the following steps in the above sentence. Isn't it redundant?

Sorry, It's my mistake.
 I have removed `Please try the following` from the document.

2021-05-17 00:21 UTC, feeblefakie approved these changes
LGTM

2021-05-17 00:30 UTC, tei-k approved these changes

2021-05-17 00:35 UTC, merged